/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lab;
import com.mis.model.FileTableModel;
import com.mis.util.DaoFactory;
import java.io.File;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrator
 */
public class NewJFrame extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        selectButton2 = new javax.swing.JButton();
        deleteButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        jTextField1.setText("请输入文件路径：");
        jTextField1.setToolTipText("");

        jButton1.setText("写入");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(fileModel);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setMaximumSize(new java.awt.Dimension(500, 400));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        selectButton2.setText("查询");
        selectButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButton2ActionPerformed(evt);
            }
        });

        deleteButton3.setText("删除");
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("树");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(selectButton2)
                            .addComponent(deleteButton3)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //写入
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             String str = jTextField1.getText().trim();
        if ("".equals(str)) {
            JOptionPane.showMessageDialog(this, "请输入路径名");
        } else {                          
		String path = jTextField1.getText().toString();
		File file = new File(path);
                if(!file.exists()){
                    JOptionPane.showMessageDialog(this, "该路径不存在");
                }else{
		LinkedList<File> list = new LinkedList<File>();
		File[] fs =file.listFiles();
		for (File f:fs) {
			if(f.isDirectory()) {
				jTextArea1.append("文件夹：" +f.getAbsolutePath()+"上级路径"+f.getParent()+"\n");
                                DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());
				list.add(f);
				
			}else {
                            if(f.getName().split("\\.").length==1){
                                jTextArea1.append("上级路径"+f.getParent()+"最后修改时间"+new Date(f.lastModified())+"文件大小"+f.length()+"文件名"+f.getName().split("\\.")[0]+"\n");
				DaoFactory.igetFilefolder().insert(f.getAbsolutePath(),new Date(f.lastModified()), f.length(), f.getName().split("\\.")[0],null);				
				DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());
                            }else{
				jTextArea1.append("上级路径"+f.getParent()+"最后修改时间"+new Date(f.lastModified())+"文件大小"+f.length()+"文件名"+f.getName().substring(0, f.getName().lastIndexOf("."))+"文件类型"+f.getName().substring(f.getName().lastIndexOf("."))+"\n");
				DaoFactory.igetFilefolder().insert(f.getAbsolutePath(),new Date(f.lastModified()), f.length(), f.getName().substring(0, f.getName().lastIndexOf(".")), f.getName().substring(f.getName().lastIndexOf(".")));				
				DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());   
                            }                             
			}
		}
                
		File temp_file;
		while(!list.isEmpty()) {
			temp_file = list.removeFirst();
			fs = temp_file.listFiles();
			for (File f:fs) {
				if(f.isDirectory()) {
                                        jTextArea1.append("文件夹：" +f.getAbsolutePath()+"上级路径"+f.getParent()+"\n");					
					DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());
                                        list.add(f);
				}else {
					if(f.getName().split("\\.").length==1){
                                jTextArea1.append("上级路径"+f.getParent()+"最后修改时间"+new Date(f.lastModified())+"文件大小"+f.length()+"文件名"+f.getName().split("\\.")[0]+"\n");
				DaoFactory.igetFilefolder().insert(f.getAbsolutePath(),new Date(f.lastModified()), f.length(), f.getName().split("\\.")[0],null);				
				DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());
                            }else{
				jTextArea1.append("上级路径"+f.getParent()+"最后修改时间"+new Date(f.lastModified())+"文件大小"+f.length()+"文件名"+f.getName().substring(0, f.getName().lastIndexOf("."))+"文件类型"+f.getName().substring(f.getName().lastIndexOf("."))+"\n");
				DaoFactory.igetFilefolder().insert(f.getAbsolutePath(),new Date(f.lastModified()), f.length(), f.getName().substring(0, f.getName().lastIndexOf(".")), f.getName().substring(f.getName().lastIndexOf(".")));				
				DaoFactory.igetFilefolder().insert_two(f.getParent(), f.getAbsolutePath());   
                            }      
			}
		}
                }
                fileModel = new FileTableModel();
                jTable1.setModel(fileModel);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //查询
    private void selectButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButton2ActionPerformed
        String str = jTextField1.getText().trim();
        if ("".equals(str)) {
            fileModel = new FileTableModel();
        } else {
            fileModel = new FileTableModel(str);
        }
// 设置表格模型
        jTable1.setModel(fileModel);
    }//GEN-LAST:event_selectButton2ActionPerformed
    //删除
    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton3ActionPerformed
        int rowNum = jTable1.getSelectedRow();
        String route = (String) jTable1.getValueAt(rowNum, 0);
        if (rowNum >= 0) {
            int choise = JOptionPane.showConfirmDialog(this, "是否要删除该条信息", "提示", JOptionPane.YES_NO_OPTION);
            if (choise == JOptionPane.YES_OPTION) {
                if (!DaoFactory.igetFilefolder().delete(route)) {
                    JOptionPane.showMessageDialog(this, "删除失败");
                }
                fileModel = new FileTableModel();
                jTable1.setModel(fileModel);
            }
        } else {
            JOptionPane.showMessageDialog(this, "请选择要删除信息！");
        }// TODO add your handling code here:
    }//GEN-LAST:event_deleteButton3ActionPerformed
    //行点击事件
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int rowNum = jTable1.getSelectedRow();
        if (rowNum >= 0) {
// 获取所选择行的第0 列的值，也就是学号的值
            String sno = (String) jTable1.getValueAt(rowNum, 3);
            jTextField1.setText(sno);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        List<String> strs;
        String str = jTextField1.getText().toString();      
        strs = DaoFactory.igetFilefolder().select_tree(str);
        for (String st:strs){
            jTextArea1.append("|"+st+"\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton selectButton2;
    // End of variables declaration//GEN-END:variables
    private FileTableModel fileModel = new FileTableModel();
}
